# Generated by Django 5.2 on 2025-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
